# Generated by Django 6.1 on 2026-08-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mood',
            name='stress_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
